### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 66: illegal multibyte sequence

### ISSUE THREAD

**Issue by handbye** [ExpLangcn/WanLi#13]
win10 报以下错误：
```shell
Traceback (most recent call last):
  File "WanLi.py", line 3, in <module>
    import core.vulscan as vulscan
  File "D:\WanLi\core\vulscan.py", line 11, in <module>
    config = yaml.load(f, Loader=yaml.CLoader)
  File "C:\Users\z\anaconda3\envs\hack\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\z\anaconda3\envs\hack\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml\_yaml.pyx", line 668, in yaml._yaml.CParser.get_single_node
  File "yaml\_yaml.pyx", line 858, in yaml._yaml.CParser._parse_next_event
  File "yaml\_yaml.pyx", line 867, in yaml._yaml.input_handler
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 66: illegal multibyte sequence
```

**Comment by ExpLangcn** [comment]
config.yaml的中文删掉试试。

**Comment by handbye** [comment]
删掉中文问题解决
