### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by h4x0rl33t** [ExpLangcn/WanLi#4]
C:\Users\24751\Desktop\WanLi-1.2>python WanLi.py
Traceback (most recent call last):
  File "C:\Users\24751\Desktop\WanLi-1.2\WanLi.py", line 8, in <module>
    import lib.cmd.wanli
  File "C:\Users\24751\Desktop\WanLi-1.2\lib\cmd\wanli.py", line 4, in <module>
    import config.config
  File "C:\Users\24751\Desktop\WanLi-1.2\config\config.py", line 6
    PYTHON = "C:\Users\24751\AppData\Local\Programs\Python\Python38-32"
                                                                       ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by ExpLangcn** [comment]
PYTHON = "C:\Users\24751\AppData\Local\Programs\Python\Python38-32"
路径错误 且 \ 要用 \\

https://github.com/ExpLangcn/WanLi/wiki/Help---%E5%B8%AE%E5%8A%A9
