### ISSUE TITLE
windows10 运行domain报错，

### ISSUE THREAD

**Issue by B1tters** [ExpLangcn/WanLi#9]
panic: couldn't load wpcap.dll

goroutine 1 [running]:
github.com/google/gopacket/pcap.pcapLibVersion(0x252f9caa800, 0x252f9cbffff)
        C:/Users/Administrator/go/pkg/mod/github.com/google/gopacket@v1.1.18/pcap/pcap_windows.go:556 +0xaf
github.com/google/gopacket/pcap.Version(...)
        C:/Users/Administrator/go/pkg/mod/github.com/google/gopacket@v1.1.18/pcap/pcap.go:587
ksubdomain/core.Start(0xc000099cc0)
        Y:/GolandProjects/ksubdomain/core/start.go:21 +0x65
main.main()
        Y:/GolandProjects/ksubdomain/cmd/ksubdomain.go:45 +0x3c
[FTL] Could not run enumeration: write /dev/stdout: The pipe is being closed.

**Comment by ExpLangcn** [comment]
等等到晚上，我会更新新的版本，新的版本可以直接用docker搭建。

**Comment by B1tters** [comment]
解决了，没装winpcap，抱歉

**Comment by Danyhug** [comment]
> 等等到晚上，我会更新新的版本，新的版本可以直接用docker搭建。

新版还没更新吗QAQ
